build_task: pipelines/gradle/tasks/gradle-assemble.yml
deploy_dev_task: pipelines/cf/tasks/blue-green-deploy.yml

app_name: roster
jar_name: gmulder-roster

github_app_repo_uri: https://github.com/mulderga/roster-gradle.git
github_app_repo_branch: master

github_pipelines_repo_uri: https://github.com/mulderga/training-pipelines-initial.git
github_pipelines_repo_branch: master

version_bucket: rscale-training-bucket
version_bucket_region_name: us-west-2

version_key: gmulder-roster-version
initial_version: 0.0.1

artifact_regexp: gmulder-roster-(.*).jar
artifact_bucket: rscale-training-bucket
artifact_bucket_region_name: us-west-2

cf_dev_api: api.run.pivotal.io
cf_dev_organization: rscale-training-4
cf_dev_space: gerard.mulder@cgi.com
cf_dev_hostname: roster-sphagnous-cephalom
cf_dev_domain: cfapps.io
cf_dev_manifest: manifest-dev.yml
